name: Flask App Pipeline

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Python version 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run Pylint
        uses: sunnysid3up/python-linter@master
        with:
          source: "./hello"
          mypy-options: "--ignore-missing-imports --show-error-codes"

  test:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Python version 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Run tests
        run: pytest

  build-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Git SHA and set environment variable
        run: |
          git rev-parse --short HEAD > image_tag
          echo "::set-env name=IMAGE_TAG::$(cat image_tag)"

      - uses: actions/checkout@v4
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: flask-app:${{ env.IMAGE_TAG }}
          file: Dockerfile

